import 'package:firebase_core/firebase_core.dart';
import 'package:firebase_messaging/firebase_messaging.dart';
import 'package:flutter/foundation.dart';
import 'package:flutter/widgets.dart';

import 'github_service.dart';
import 'storage_service.dart';
import 'wallpaper_service.dart';
import '../models/models.dart';
import '../firebase_options.dart'; // Auto-generated by flutterfire

// ══════════════════════════════════════════════════════════════════════════
// 📨 FCM SERVICE - Background Updates
// ══════════════════════════════════════════════════════════════════════════
// Handles "Silent Push" triggers from Cloud Functions to update wallpaper.
// ══════════════════════════════════════════════════════════════════════════

// Must be a top-level function
@pragma('vm:entry-point')
Future<void> _firebaseMessagingBackgroundHandler(RemoteMessage message) async {
  // If we receive a notification payload, it might show a system tray notification.
  // We expect "data-only" messages for silent updates.
  try {
    if (kDebugMode) debugPrint('FCM: Background notification received');

    // 1. Initialize Flutter & Firebase
    WidgetsFlutterBinding.ensureInitialized();
    await Firebase.initializeApp(options: DefaultFirebaseOptions.currentPlatform);
    
    // 2. Initialize Storage
    await StorageService.init();

    // 3. Check Credentials
    final username = StorageService.getUsername();
    final token = await StorageService.getToken();

    if (username == null || token == null) {
      if (kDebugMode) debugPrint('FCM: Missing credentials, aborting update');
      return;
    }

    // 3b. Check Auto-Update Preference
    if (!StorageService.getAutoUpdate()) {
      if (kDebugMode) print("🛑 [FCM] Auto-update disabled by user, skipping.");
      return;
    }

    // 4. Fetch Data
    if (kDebugMode) debugPrint('FCM: Fetching contribution data...');
    final contributions = await GitHubService.fetchContributions(
      username: username,
      token: token,
    );

    // 5. Update Storage
    await StorageService.setCachedData(contributions);
    await StorageService.setLastUpdate(DateTime.now());

    // 6. Generate Wallpaper
    if (kDebugMode) print("🎨 [FCM] Generating wallpaper...");
    final savedConfig = StorageService.getWallpaperConfig() ?? WallpaperConfig.defaults();
    
    await WallpaperService.generateAndSetWallpaper(
      data: contributions, 
      config: savedConfig,
    );
    
    if (kDebugMode) print("✅ [FCM] Wallpaper updated successfully!");

  } catch (e, stack) {
    if (kDebugMode) print("❌ [FCM] Error: $e\n$stack");
  }
}

class FcmService {
  static final FirebaseMessaging _messaging = FirebaseMessaging.instance;

  /// Initialize FCM and register handlers
  static Future<void> init() async {
    // 1. Register Background Handler
    FirebaseMessaging.onBackgroundMessage(_firebaseMessagingBackgroundHandler);

    // 2. Request Permissions (iOS/Android 13+)
    NotificationSettings settings = await _messaging.requestPermission(
      alert: true,
      badge: true,
      sound: true,
      provisional: false,
    );

    if (kDebugMode) {
      print('🔔 [FCM] Permission status: ${settings.authorizationStatus}');
    }

    // 3. Subscribe to Daily Updates Topic
    // This allows the server to blast "tick" messages to everyone subscribed.
    await _messaging.subscribeToTopic('daily-updates');
    if (kDebugMode) print('📡 [FCM] Subscribed to "daily-updates" topic');


  }
}
