// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDD1CVX-40IF7Ac68yMoZ2-ySPaILEjlS0',
    appId: '1:826591895293:android:91505e5ae02eef985d6894',
    messagingSenderId: '826591895293',
    projectId: 'gitwall-d63cc',
    storageBucket: 'gitwall-d63cc.firebasestorage.app',
  );

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDUOseD3NbhJ8N-QP5l6MGHUxO9iom7F_Q',
    appId: '1:826591895293:web:16c61e38e4818f165d6894',
    messagingSenderId: '826591895293',
    projectId: 'gitwall-d63cc',
    authDomain: 'gitwall-d63cc.firebaseapp.com',
    storageBucket: 'gitwall-d63cc.firebasestorage.app',
    measurementId: 'G-9TFBGFEV03',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAZinem2-Kr_lviJx8UFILpU9DZWcX1Yng',
    appId: '1:826591895293:ios:b441ed2d57690dcf5d6894',
    messagingSenderId: '826591895293',
    projectId: 'gitwall-d63cc',
    storageBucket: 'gitwall-d63cc.firebasestorage.app',
    iosBundleId: 'com.example.githubWallpaper',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAZinem2-Kr_lviJx8UFILpU9DZWcX1Yng',
    appId: '1:826591895293:ios:b441ed2d57690dcf5d6894',
    messagingSenderId: '826591895293',
    projectId: 'gitwall-d63cc',
    storageBucket: 'gitwall-d63cc.firebasestorage.app',
    iosBundleId: 'com.example.githubWallpaper',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDUOseD3NbhJ8N-QP5l6MGHUxO9iom7F_Q',
    appId: '1:826591895293:web:122a427146b7437f5d6894',
    messagingSenderId: '826591895293',
    projectId: 'gitwall-d63cc',
    authDomain: 'gitwall-d63cc.firebaseapp.com',
    storageBucket: 'gitwall-d63cc.firebasestorage.app',
    measurementId: 'G-SF2V3498F1',
  );

}